### ISSUE TITLE
how to use this tool? 

### ISSUE THREAD

**Issue by zkcsmxz** [PridaLab/rippl-AI#4]
Hi 
I try the CNN2D architecture, i think it fit to my data well.I used open ephys and liner probe.
I have a question is there are wey to distinguish Ripple types? Like SW-Ripple, Ripple-noSW and Pop-Sync?
Thanks a lot

**Comment by zkcsmxz** [comment]
by the way I used Open ephys and 64channel probe for the recording

**Comment by acnavasolive** [comment]
Hello! In principle, this tool does not offer this classification per se, just detects it. However, there are ways in which you might be able to do it. One way would be inspecting the CNN kernels - in Fig6 of our elife paper (https://elifesciences.org/articles/77772) we show how this is possible. So imagine: you could try to take examples of your data you classify as SW ripples, SW no ripples and Population synchrony, and see which kernels are systematically activated for each of them. This would give you both detection and type at the same time, but we didn't have time to try it yet. I hope this is helpful! Let us know how it goes!
