### ISSUE TITLE
Package version conflicts

### ISSUE THREAD

**Issue by j-moore94** [PridaLab/rippl-AI#5]
Hi,
I'm trying to use the toolbox but running into issues with package versions, particularly numpy. Would it be possible to share which versions of numpy, scipy etc. were used please? (or an environment.yml file)
Thanks a lot!
Joe

**Comment by acnavasolive** [comment]
Hi Joe!

These are the packages that I'm using. I will update the README with them, it's true that can easily give problems. Let me know if it works!

h5py==3.11.0
imbalanced-learn==0.12.2
imblearn==0.0
ipython==8.18.1
keras==2.11.0
numpy==1.26.4
pandas==2.2.2
pip==23.3.1
python==3.9.19
scikit-learn==1.1.2
scipy==1.13.0
tensorflow==2.11.0
xgboost==1.6.1

**Comment by j-moore94** [comment]
Hi Andrea, thanks for the reply! I tried numpy 1.23 and that seemed to fix the error I was getting. But yeah, using the environment instuctions that were on the README gives numpy 2.0, which caused issues.

The toolbox is great though! :)

**Comment by acnavasolive** [comment]
I see! Thanks for sharing, we will keep an eye! I will change the README then!
